### ISSUE TITLE
Sheath

### ISSUE THREAD

**Issue by Strike5223** [MalibuTechTeam/mbt_malisling#20]
I am trying to use a katana and want to have the sheathed katana model show on my back is this possible?

**Comment by matahombres** [comment]
I was passing by since I was going to make a pull request, so I'll answer you....
The script uses this native to take the model of the weapon: [GetWeapontypeModel](https://docs.fivem.net/natives/?_0xF46CDC33180FDA94)
If you have your katana configured as a weapon. Just configure it in data/weapons.lua.
